// The AI coach panel: requests coaching for a saved analysis and renders it.
import { el, renderScoreBars, requestJson } from "./common.js";

const $ = (id) => document.getElementById(id);
let activeAnalysisId = null;

function fillList(listId, items, render) {
  const list = $(listId);
  list.textContent = "";
  items.forEach((item) => {
    const li = el("li");
    render(li, item);
    list.appendChild(li);
  });
}

function showMessage(title, message, canRetry) {
  $("contentScore").textContent = "-";
  $("coachTitle").textContent = title;
  $("coachMeta").textContent = message;
  $("coachBody").classList.add("hidden");
  $("retryCoachBtn").classList.toggle("hidden", !canRetry);
}

function renderCoach(coach) {
  $("contentScore").textContent = coach.content_score;
  $("coachTitle").textContent = coach.on_topic ? "Content review" : "Content review: off-topic";
  const meta = coach.meta || {};
  $("coachMeta").textContent = meta.model
    ? `Generated by ${meta.model} via ${meta.provider}${meta.latency_ms ? ` in ${(meta.latency_ms / 1000).toFixed(1)}s` : ""}`
    : "";
  $("coachSummary").textContent = coach.summary;
  renderScoreBars($("contentBreakdown"), coach.dimensions, coach.content_scores);

  const { framework } = coach;
  $("frameworkTitle").textContent = `${framework.name} check`;
  const chips = $("frameworkChips");
  chips.textContent = "";
  framework.parts.forEach((part) => {
    const present = framework.present.includes(part);
    chips.appendChild(el("span", present ? "chip chip-present" : "chip chip-missing", `${present ? "✓" : "✗"} ${part}`));
  });

  fillList("coachStrengths", coach.strengths, (li, text) => {
    li.textContent = text;
  });
  fillList("coachImprovements", coach.improvements, (li, item) => {
    li.append(el("b", "", item.issue), el("br"), item.suggestion);
  });
  $("coachTopic").textContent = coach.topic_feedback;
  $("improvedTitle").textContent =
    coach.improved_answer_type === "template" ? "A structure to follow (fill in your own details)" : "A stronger version of your answer";
  $("improvedAnswer").textContent = coach.improved_answer;
  $("coachBody").classList.remove("hidden");
  $("retryCoachBtn").classList.add("hidden");
}

export function hideCoach() {
  activeAnalysisId = null;
  $("coachPanel").classList.add("hidden");
}

export async function requestCoaching(analysisId, onSessionExpired) {
  activeAnalysisId = analysisId;
  $("coachPanel").classList.remove("hidden");
  showMessage("Reviewing your answer...", "The AI coach is reading your transcript.", false);
  try {
    const data = await requestJson(`/analyses/${analysisId}/coach`, { method: "POST" });
    if (analysisId === activeAnalysisId) renderCoach(data.coach);
  } catch (error) {
    if (analysisId !== activeAnalysisId) return;
    if (error.status === 401) {
      onSessionExpired();
      return;
    }
    showMessage("AI coach unavailable", error.message, [429, 503, 504].includes(error.status));
  }
}

export function initCoach(onSessionExpired) {
  $("retryCoachBtn").addEventListener("click", () => {
    if (activeAnalysisId) requestCoaching(activeAnalysisId, onSessionExpired);
  });
  $("copyImprovedBtn").addEventListener("click", async () => {
    const button = $("copyImprovedBtn");
    try {
      await navigator.clipboard.writeText($("improvedAnswer").textContent);
      button.textContent = "Copied";
    } catch {
      button.textContent = "Copy failed";
    }
    setTimeout(() => {
      button.textContent = "Copy";
    }, 1500);
  });
}
