// AI coach panel (cloned from #coachTemplate): requests coaching for a saved analysis and renders it.
import { el, renderScoreBars, requestJson } from "./common.js";

function fillList(list, items, render) {
  list.textContent = "";
  items.forEach((item) => {
    const li = el("li");
    render(li, item);
    list.appendChild(li);
  });
}

export function createCoachView(container, onSessionExpired) {
  const root = document.getElementById("coachTemplate").content.firstElementChild.cloneNode(true);
  root.classList.add("hidden");
  container.appendChild(root);
  const part = (name) => root.querySelector(`[data-el="${name}"]`);
  let activeId = null;

  function showMessage(title, message, canRetry) {
    part("contentScore").textContent = "-";
    part("coachTitle").textContent = title;
    part("coachMeta").textContent = message;
    part("coachBody").classList.add("hidden");
    part("retryCoachBtn").classList.toggle("hidden", !canRetry);
  }

  function show(coach) {
    root.classList.remove("hidden");
    part("contentScore").textContent = coach.content_score;
    part("coachTitle").textContent = coach.on_topic ? "Content review" : "Content review: off-topic";
    const meta = coach.meta || {};
    part("coachMeta").textContent = meta.model
      ? `Generated by ${meta.model} via ${meta.provider}${meta.latency_ms ? ` in ${(meta.latency_ms / 1000).toFixed(1)}s` : ""}`
      : "";
    part("coachSummary").textContent = coach.summary;
    renderScoreBars(part("contentBreakdown"), coach.dimensions, coach.content_scores);

    const { framework } = coach;
    part("frameworkTitle").textContent = `${framework.name} check`;
    const chips = part("frameworkChips");
    chips.textContent = "";
    framework.parts.forEach((item) => {
      const present = framework.present.includes(item);
      chips.appendChild(el("span", present ? "chip chip-present" : "chip chip-missing", `${present ? "✓" : "✗"} ${item}`));
    });

    fillList(part("coachStrengths"), coach.strengths, (li, text) => {
      li.textContent = text;
    });
    fillList(part("coachImprovements"), coach.improvements, (li, item) => {
      li.append(el("b", "", item.issue), el("br"), item.suggestion);
    });
    part("coachTopic").textContent = coach.topic_feedback;
    part("improvedTitle").textContent =
      coach.improved_answer_type === "template" ? "A structure to follow (fill in your own details)" : "A stronger version of your answer";
    part("improvedAnswer").textContent = coach.improved_answer;
    part("coachBody").classList.remove("hidden");
    part("retryCoachBtn").classList.add("hidden");
  }

  async function request(analysisId) {
    activeId = analysisId;
    root.classList.remove("hidden");
    showMessage("Reviewing your answer...", "The AI coach is reading your transcript.", false);
    try {
      const data = await requestJson(`/analyses/${analysisId}/coach`, { method: "POST" });
      if (analysisId === activeId) show(data.coach);
    } catch (error) {
      if (analysisId !== activeId) return;
      if (error.status === 401) {
        onSessionExpired();
        return;
      }
      showMessage("AI coach unavailable", error.message, [429, 503, 504].includes(error.status));
    }
  }

  part("retryCoachBtn").addEventListener("click", () => {
    if (activeId) request(activeId);
  });
  part("copyImprovedBtn").addEventListener("click", async () => {
    const button = part("copyImprovedBtn");
    try {
      await navigator.clipboard.writeText(part("improvedAnswer").textContent);
      button.textContent = "Copied";
    } catch {
      button.textContent = "Copy failed";
    }
    setTimeout(() => {
      button.textContent = "Copy";
    }, 1500);
  });

  return {
    request,
    show,
    hide() {
      activeId = null;
      root.classList.add("hidden");
    },
  };
}
